/** Canonical CRM permission keys (DB `role_permissions.permission_key`). */

export const ALL_PERMISSION_KEYS = [
  "contacts_view",
  "contacts_create",
  "contacts_edit",
  "contacts_delete",
  "contacts_export",
  "contacts_import",
  "requests_view",
  "requests_create",
  "requests_edit",
  "requests_delete",
  "campaigns_view",
  "campaigns_create",
  "campaigns_start",
  "tasks_view",
  "tasks_create",
  "tasks_assign",
  "analytics_view",
  "documents_view",
  "documents_upload",
  "settings_view",
  "settings_edit",
  "users_manage",
  "roles_manage",
  "events_view",
  "events_create",
  "volunteers_view",
  "polls_view",
  "polls_create",
  "alexandra_use",
  "alexandra_bulk_delete",
  "alexandra_bulk_update",
  "alexandra_import",
  "alexandra_tool_bulk_delete_contacts",
  "alexandra_tool_bulk_update_contacts",
  "alexandra_tool_start_campaign",
  "alexandra_tool_send_whatsapp",
  "alexandra_tool_export_contacts",
  "alexandra_tool_create_user",
  "alexandra_tool_delete_data",
  "retell_call",
  "whatsapp_send",
  "export_data",
  "contacts_bulk",
  "requests_complete",
  "requests_reject",
  "requests_assign",
  "requests_scheduler_view",
  "requests_scheduler_schedule",
  "requests_scheduler_complete",
  "requests_scheduler_reject",
  "requests_scheduler_ai_summary",
  "data_tools_view",
  "data_tools_bulk_delete",
  "data_tools_bulk_edit",
  "data_tools_export_vcf",
  "data_tools_export_excel",
  "access_code_view",
  "access_code_revoke",
] as const;

export type PermissionKey = (typeof ALL_PERMISSION_KEYS)[number];

/** Suggested defaults when seeding new keys (staff ≈ caller). */
export const PERMISSION_ROLE_DEFAULTS: Record<PermissionKey, readonly ("admin" | "manager" | "caller")[]> = {
  contacts_view: ["admin", "manager", "caller"],
  contacts_create: ["admin", "manager", "caller"],
  contacts_edit: ["admin", "manager", "caller"],
  contacts_delete: ["admin"],
  contacts_export: ["admin", "manager"],
  contacts_import: ["admin", "manager"],
  contacts_bulk: ["admin", "manager"],
  requests_view: ["admin", "manager", "caller"],
  requests_create: ["admin", "manager", "caller"],
  requests_edit: ["admin", "manager", "caller"],
  requests_delete: ["admin"],
  requests_complete: ["admin", "manager"],
  requests_reject: ["admin", "manager"],
  requests_assign: ["admin", "manager"],
  requests_scheduler_view: ["admin", "manager", "caller"],
  requests_scheduler_schedule: ["admin", "manager"],
  requests_scheduler_complete: ["admin", "manager"],
  requests_scheduler_reject: ["admin", "manager"],
  requests_scheduler_ai_summary: ["admin", "manager", "caller"],
  campaigns_view: ["admin", "manager", "caller"],
  campaigns_create: ["admin", "manager", "caller"],
  campaigns_start: ["admin", "manager", "caller"],
  tasks_view: ["admin", "manager", "caller"],
  tasks_create: ["admin", "manager", "caller"],
  tasks_assign: ["admin", "manager", "caller"],
  analytics_view: ["admin", "manager", "caller"],
  documents_view: ["admin", "manager", "caller"],
  documents_upload: ["admin", "manager", "caller"],
  settings_view: ["admin", "manager", "caller"],
  settings_edit: ["admin", "manager"],
  users_manage: ["admin"],
  roles_manage: ["admin"],
  events_view: ["admin", "manager", "caller"],
  events_create: ["admin", "manager", "caller"],
  volunteers_view: ["admin", "manager", "caller"],
  polls_view: ["admin", "manager", "caller"],
  polls_create: ["admin", "manager", "caller"],
  alexandra_use: ["admin", "manager", "caller"],
  alexandra_bulk_delete: ["admin", "manager"],
  alexandra_bulk_update: ["admin", "manager"],
  alexandra_import: ["admin", "manager"],
  alexandra_tool_bulk_delete_contacts: ["admin", "manager"],
  alexandra_tool_bulk_update_contacts: ["admin", "manager"],
  alexandra_tool_start_campaign: ["admin", "manager"],
  alexandra_tool_send_whatsapp: ["admin", "manager"],
  alexandra_tool_export_contacts: ["admin", "manager"],
  alexandra_tool_create_user: ["admin"],
  alexandra_tool_delete_data: ["admin"],
  retell_call: ["admin", "manager", "caller"],
  whatsapp_send: ["admin", "manager", "caller"],
  export_data: ["admin", "manager"],
  data_tools_view: ["admin", "manager"],
  data_tools_bulk_delete: ["admin"],
  data_tools_bulk_edit: ["admin", "manager"],
  data_tools_export_vcf: ["admin", "manager"],
  data_tools_export_excel: ["admin", "manager"],
  access_code_view: ["admin"],
  access_code_revoke: ["admin"],
};

export type PermissionCategoryId =
  | "contacts"
  | "requests"
  | "requests_scheduler"
  | "campaigns"
  | "data_tools"
  | "tools"
  | "access"
  | "alexandra"
  | "alexandra_tools"
  | "settings";

export type PermissionCategory = {
  id: PermissionCategoryId;
  label: string;
  keys: readonly PermissionKey[];
};

export const PERMISSION_CATEGORIES: readonly PermissionCategory[] = [
  {
    id: "contacts",
    label: "Επαφές",
    keys: [
      "contacts_view",
      "contacts_create",
      "contacts_edit",
      "contacts_delete",
      "contacts_export",
      "contacts_import",
      "contacts_bulk",
    ],
  },
  {
    id: "requests",
    label: "Αιτήματα",
    keys: [
      "requests_view",
      "requests_create",
      "requests_edit",
      "requests_delete",
      "requests_complete",
      "requests_reject",
      "requests_assign",
    ],
  },
  {
    id: "requests_scheduler",
    label: "Προγραμματισμός αιτημάτων",
    keys: [
      "requests_scheduler_view",
      "requests_scheduler_schedule",
      "requests_scheduler_complete",
      "requests_scheduler_reject",
      "requests_scheduler_ai_summary",
    ],
  },
  {
    id: "data_tools",
    label: "Εργαλεία δεδομένων",
    keys: [
      "data_tools_view",
      "data_tools_bulk_delete",
      "data_tools_bulk_edit",
      "data_tools_export_vcf",
      "data_tools_export_excel",
    ],
  },
  {
    id: "campaigns",
    label: "Καμπάνιες",
    keys: ["campaigns_view", "campaigns_create", "campaigns_start"],
  },
  {
    id: "tools",
    label: "Εργαλεία",
    keys: [
      "tasks_view",
      "tasks_create",
      "tasks_assign",
      "analytics_view",
      "documents_view",
      "documents_upload",
      "events_view",
      "events_create",
      "volunteers_view",
      "polls_view",
      "polls_create",
      "retell_call",
      "whatsapp_send",
      "export_data",
    ],
  },
  {
    id: "alexandra",
    label: "Αλεξάνδρα",
    keys: [
      "alexandra_use",
      "alexandra_bulk_delete",
      "alexandra_bulk_update",
      "alexandra_import",
    ],
  },
  {
    id: "alexandra_tools",
    label: "Αλεξάνδρα — εργαλεία",
    keys: [
      "alexandra_tool_bulk_delete_contacts",
      "alexandra_tool_bulk_update_contacts",
      "alexandra_tool_start_campaign",
      "alexandra_tool_send_whatsapp",
      "alexandra_tool_export_contacts",
      "alexandra_tool_create_user",
      "alexandra_tool_delete_data",
    ],
  },
  {
    id: "access",
    label: "Ασφάλεια πρόσβασης",
    keys: ["access_code_view", "access_code_revoke"],
  },
  {
    id: "settings",
    label: "Ρυθμίσεις",
    keys: ["settings_view", "settings_edit", "users_manage", "roles_manage"],
  },
] as const;

export const PERMISSION_LABELS: Record<PermissionKey, string> = {
  contacts_view: "Προβολή επαφών",
  contacts_create: "Δημιουργία επαφών",
  contacts_edit: "Επεξεργασία επαφών",
  contacts_delete: "Διαγραφή επαφών",
  contacts_export: "Εξαγωγή επαφών",
  contacts_import: "Εισαγωγή επαφών",
  contacts_bulk: "Μαζικές ενέργειες επαφών",
  requests_view: "Προβολή αιτημάτων",
  requests_create: "Δημιουργία αιτημάτων",
  requests_edit: "Επεξεργασία αιτημάτων",
  requests_delete: "Διαγραφή αιτημάτων",
  requests_complete: "Ολοκλήρωση αιτήματος (γρήγορη)",
  requests_reject: "Απόρριψη αιτήματος",
  requests_assign: "Ανάθεση αιτήματος",
  requests_scheduler_view: "Προγραμματισμός — προβολή",
  requests_scheduler_schedule: "Προγραμματισμός — χρονοπρογραμματισμός",
  requests_scheduler_complete: "Προγραμματισμός — ολοκλήρωση",
  requests_scheduler_reject: "Προγραμματισμός — απόρριψη",
  requests_scheduler_ai_summary: "Προγραμματισμός — AI περίληψη",
  data_tools_view: "Εργαλεία δεδομένων — προβολή",
  data_tools_bulk_delete: "Εργαλεία — μαζική διαγραφή",
  data_tools_bulk_edit: "Εργαλεία — μαζική επεξεργασία",
  data_tools_export_vcf: "Εξαγωγή vCard",
  data_tools_export_excel: "Εξαγωγή Excel",
  access_code_view: "Κλειδαριθμός — προβολή",
  access_code_revoke: "Κλειδαριθμός — ανάκληση",
  campaigns_view: "Προβολή καμπανιών",
  campaigns_create: "Δημιουργία καμπανιών",
  campaigns_start: "Εκκίνηση κλήσεων καμπάνιας",
  tasks_view: "Προβολή εργασιών",
  tasks_create: "Δημιουργία εργασιών",
  tasks_assign: "Ανάθεση εργασιών",
  analytics_view: "Αναλυτικά",
  documents_view: "Έγγραφα — προβολή",
  documents_upload: "Έγγραφα — μεταφόρτωση",
  settings_view: "Ρυθμίσεις — προβολή",
  settings_edit: "Ρυθμίσεις — επεξεργασία",
  users_manage: "Διαχείριση χρηστών",
  roles_manage: "Διαχείριση ρόλων",
  events_view: "Εκδηλώσεις — προβολή",
  events_create: "Εκδηλώσεις — δημιουργία",
  volunteers_view: "Εθελοντές",
  polls_view: "Δημοσκοπήσεις — προβολή",
  polls_create: "Δημοσκοπήσεις — δημιουργία",
  alexandra_use: "Χρήση Αλεξάνδρας",
  alexandra_bulk_delete: "Αλεξάνδρα — μαζική διαγραφή",
  alexandra_bulk_update: "Αλεξάνδρα — μαζική ενημέρωση",
  alexandra_import: "Αλεξάνδρα — εισαγωγή",
  alexandra_tool_bulk_delete_contacts: "Εργαλείο: μαζική διαγραφή επαφών",
  alexandra_tool_bulk_update_contacts: "Εργαλείο: μαζική ενημέρωση επαφών",
  alexandra_tool_start_campaign: "Εργαλείο: εκκίνηση καμπάνιας",
  alexandra_tool_send_whatsapp: "Εργαλείο: WhatsApp",
  alexandra_tool_export_contacts: "Εργαλείο: εξαγωγή επαφών",
  alexandra_tool_create_user: "Εργαλείο: δημιουργία χρήστη",
  alexandra_tool_delete_data: "Εργαλείο: διαγραφή δεδομένων",
  retell_call: "Retell — κλήσεις",
  whatsapp_send: "WhatsApp — αποστολή",
  export_data: "Εξαγωγή δεδομένων (εργαλεία)",
};

export const ALEXANDRA_TOOL_KEYS = PERMISSION_CATEGORIES.find((c) => c.id === "alexandra_tools")!.keys;
