/** Canonical CRM permission keys (DB `role_permissions.permission_key`). */

export const ALL_PERMISSION_KEYS = [
  "contacts_view",
  "contacts_create",
  "contacts_edit",
  "contacts_delete",
  "contacts_export",
  "contacts_import",
  "requests_view",
  "requests_create",
  "requests_edit",
  "requests_delete",
  "campaigns_view",
  "campaigns_create",
  "campaigns_start",
  "tasks_view",
  "tasks_create",
  "tasks_assign",
  "analytics_view",
  "documents_view",
  "documents_upload",
  "settings_view",
  "settings_edit",
  "users_manage",
  "roles_manage",
  "events_view",
  "events_create",
  "volunteers_view",
  "polls_view",
  "polls_create",
  "alexandra_use",
  "alexandra_bulk_delete",
  "alexandra_bulk_update",
  "alexandra_import",
  "alexandra_tool_bulk_delete_contacts",
  "alexandra_tool_bulk_update_contacts",
  "alexandra_tool_start_campaign",
  "alexandra_tool_send_whatsapp",
  "alexandra_tool_export_contacts",
  "alexandra_tool_create_user",
  "alexandra_tool_delete_data",
  "retell_call",
  "whatsapp_send",
  "export_data",
  "contacts_bulk",
  "requests_complete",
  "requests_reject",
  "requests_assign",
  "requests_scheduler_view",
  "requests_scheduler_schedule",
  "requests_scheduler_complete",
  "requests_scheduler_reject",
  "requests_scheduler_ai_summary",
  "data_tools_view",
  "data_tools_bulk_delete",
  "data_tools_bulk_edit",
  "data_tools_export_vcf",
  "data_tools_export_excel",
  "access_code_view",
  "access_code_revoke",
  "communication_logs_delete",
  "ai_summary_view",
] as const;

export type PermissionKey = (typeof ALL_PERMISSION_KEYS)[number];

/** Suggested defaults when seeding new keys (staff ≈ caller). */
export const PERMISSION_ROLE_DEFAULTS: Record<PermissionKey, readonly ("admin" | "manager" | "caller")[]> = {
  contacts_view: ["admin", "manager", "caller"],
  contacts_create: ["admin", "manager", "caller"],
  contacts_edit: ["admin", "manager", "caller"],
  contacts_delete: ["admin"],
  contacts_export: ["admin", "manager"],
  contacts_import: ["admin", "manager"],
  contacts_bulk: ["admin", "manager"],
  requests_view: ["admin", "manager", "caller"],
  requests_create: ["admin", "manager", "caller"],
  requests_edit: ["admin", "manager", "caller"],
  requests_delete: ["admin"],
  requests_complete: ["admin", "manager"],
  requests_reject: ["admin", "manager"],
  requests_assign: ["admin", "manager"],
  requests_scheduler_view: ["admin", "manager", "caller"],
  requests_scheduler_schedule: ["admin", "manager"],
  requests_scheduler_complete: ["admin", "manager"],
  requests_scheduler_reject: ["admin", "manager"],
  requests_scheduler_ai_summary: ["admin", "manager", "caller"],
  campaigns_view: ["admin", "manager", "caller"],
  campaigns_create: ["admin", "manager", "caller"],
  campaigns_start: ["admin", "manager", "caller"],
  tasks_view: ["admin", "manager", "caller"],
  tasks_create: ["admin", "manager", "caller"],
  tasks_assign: ["admin", "manager", "caller"],
  analytics_view: ["admin", "manager", "caller"],
  documents_view: ["admin", "manager", "caller"],
  documents_upload: ["admin", "manager", "caller"],
  settings_view: ["admin", "manager", "caller"],
  settings_edit: ["admin", "manager"],
  users_manage: ["admin"],
  roles_manage: ["admin"],
  events_view: ["admin", "manager", "caller"],
  events_create: ["admin", "manager", "caller"],
  volunteers_view: ["admin", "manager", "caller"],
  polls_view: ["admin", "manager", "caller"],
  polls_create: ["admin", "manager", "caller"],
  alexandra_use: ["admin", "manager", "caller"],
  alexandra_bulk_delete: ["admin", "manager"],
  alexandra_bulk_update: ["admin", "manager"],
  alexandra_import: ["admin", "manager"],
  alexandra_tool_bulk_delete_contacts: ["admin", "manager"],
  alexandra_tool_bulk_update_contacts: ["admin", "manager"],
  alexandra_tool_start_campaign: ["admin", "manager"],
  alexandra_tool_send_whatsapp: ["admin", "manager"],
  alexandra_tool_export_contacts: ["admin", "manager"],
  alexandra_tool_create_user: ["admin"],
  alexandra_tool_delete_data: ["admin"],
  retell_call: ["admin", "manager", "caller"],
  whatsapp_send: ["admin", "manager", "caller"],
  export_data: ["admin", "manager"],
  data_tools_view: ["admin", "manager"],
  data_tools_bulk_delete: ["admin"],
  data_tools_bulk_edit: ["admin", "manager"],
  data_tools_export_vcf: ["admin", "manager"],
  data_tools_export_excel: ["admin", "manager"],
  access_code_view: ["admin"],
  access_code_revoke: ["admin"],
  communication_logs_delete: ["admin"],
  ai_summary_view: ["admin", "manager"],
};

export type PermissionCategoryId =
  | "contacts"
  | "requests"
  | "requests_scheduler"
  | "campaigns"
  | "data_tools"
  | "tools"
  | "access"
  | "alexandra"
  | "alexandra_tools"
  | "settings";

export type PermissionCategory = {
  id: PermissionCategoryId;
  label: string;
  keys: readonly PermissionKey[];
};

export const PERMISSION_TOOLTIPS: Record<PermissionKey, string> = {
  contacts_view: "Προβολή λίστας και καρτέλας επαφών",
  contacts_create: "Δημιουργία νέας επαφής",
  contacts_edit: "Επεξεργασία πεδίων επαφής",
  contacts_delete: "Διαγραφή επαφής (μόνιμη)",
  contacts_export: "Εξαγωγή επαφών σε Excel/CSV",
  contacts_import: "Εισαγωγή επαφών από αρχείο",
  contacts_bulk: "Μαζικές ενέργειες σε επαφές",
  requests_view: "Προβολή λίστας και λεπτομερειών αιτημάτων",
  requests_create: "Δημιουργία νέου αιτήματος",
  requests_edit: "Επεξεργασία αιτήματος",
  requests_delete: "Διαγραφή αιτήματος",
  requests_complete: "Γρήγορη ολοκλήρωση αιτήματος",
  requests_reject: "Απόρριψη αιτήματος",
  requests_assign: "Ανάθεση αιτήματος σε χρήστη",
  requests_scheduler_view: "Προβολή ημερολογίου προγραμματισμού",
  requests_scheduler_schedule: "Προγραμματισμός αιτήματος σε ημερομηνία",
  requests_scheduler_complete: "Ολοκλήρωση προγραμματισμένου αιτήματος",
  requests_scheduler_reject: "Απόρριψη από τον προγραμματισμό",
  requests_scheduler_ai_summary: "AI περίληψη αιτημάτων στον προγραμματισμό",
  data_tools_view: "Πρόσβαση στα εργαλεία δεδομένων (διπλότυπα, έλεγχοι)",
  data_tools_bulk_delete: "Μαζική διαγραφή επαφών μέσω εργαλείων",
  data_tools_bulk_edit: "Μαζική επεξεργασία επαφών μέσω εργαλείων",
  data_tools_export_vcf: "Εξαγωγή επαφών σε vCard (.vcf)",
  data_tools_export_excel: "Εξαγωγή επαφών σε Excel",
  campaigns_view: "Προβολή καμπανιών κλήσεων",
  campaigns_create: "Δημιουργία νέας καμπάνιας",
  campaigns_start: "Εκκίνηση κλήσεων καμπάνιας",
  tasks_view: "Προβολή εργασιών",
  tasks_create: "Δημιουργία εργασίας",
  tasks_assign: "Ανάθεση εργασίας σε χρήστη",
  analytics_view: "Προβολή αναλυτικών στατιστικών",
  documents_view: "Προβολή εγγράφων",
  documents_upload: "Μεταφόρτωση εγγράφων",
  events_view: "Προβολή εκδηλώσεων",
  events_create: "Δημιουργία εκδήλωσης",
  volunteers_view: "Προβολή εθελοντών",
  polls_view: "Προβολή δημοσκοπήσεων",
  polls_create: "Δημιουργία δημοσκόπησης",
  retell_call: "Πραγματοποίηση κλήσεων μέσω Retell AI",
  whatsapp_send: "Αποστολή μηνυμάτων WhatsApp",
  export_data: "Γενική εξαγωγή δεδομένων",
  alexandra_use: "Χρήση του AI assistant Αλεξάνδρα",
  alexandra_bulk_delete: "Μαζική διαγραφή επαφών μέσω Αλεξάνδρας",
  alexandra_bulk_update: "Μαζική ενημέρωση επαφών μέσω Αλεξάνδρας",
  alexandra_import: "Εισαγωγή δεδομένων μέσω Αλεξάνδρας",
  alexandra_tool_bulk_delete_contacts: "Εργαλείο: μαζική διαγραφή επαφών από chat",
  alexandra_tool_bulk_update_contacts: "Εργαλείο: μαζική ενημέρωση επαφών από chat",
  alexandra_tool_start_campaign: "Εργαλείο: εκκίνηση καμπάνιας από chat",
  alexandra_tool_send_whatsapp: "Εργαλείο: αποστολή WhatsApp από chat",
  alexandra_tool_export_contacts: "Εργαλείο: εξαγωγή επαφών από chat",
  alexandra_tool_create_user: "Εργαλείο: δημιουργία χρήστη CRM από chat",
  alexandra_tool_delete_data: "Εργαλείο: διαγραφή δεδομένων από chat",
  access_code_view: "Προβολή κλειδαριθμού τρέχουσας ώρας",
  access_code_revoke: "Ανάκληση πρόσβασης χρηστών",
  communication_logs_delete: "Διαγραφή καταγραφών επικοινωνίας από την καρτέλα επαφής",
  ai_summary_view: "Προβολή AI σύνοψης σε καρτέλες επαφής και αιτήματος",
  settings_view: "Προβολή σελίδας ρυθμίσεων",
  settings_edit: "Επεξεργασία ρυθμίσεων CRM",
  users_manage: "Διαχείριση χρηστών (προσθήκη/διαγραφή)",
  roles_manage: "Διαχείριση ρόλων και δικαιωμάτων",
};

export const PERMISSION_CATEGORIES: readonly PermissionCategory[] = [
  {
    id: "contacts",
    label: "ΕΠΑΦΕΣ",
    keys: [
      "contacts_view",
      "contacts_create",
      "contacts_edit",
      "contacts_delete",
      "contacts_export",
      "contacts_import",
      "contacts_bulk",
      "communication_logs_delete",
      "ai_summary_view",
    ],
  },
  {
    id: "requests",
    label: "ΑΙΤΗΜΑΤΑ",
    keys: [
      "requests_view",
      "requests_create",
      "requests_edit",
      "requests_delete",
      "requests_complete",
      "requests_reject",
      "requests_assign",
    ],
  },
  {
    id: "requests_scheduler",
    label: "ΠΡΟΓΡΑΜΜΑΤΙΣΜΟΣ ΑΙΤΗΜΑΤΩΝ",
    keys: [
      "requests_scheduler_view",
      "requests_scheduler_schedule",
      "requests_scheduler_complete",
      "requests_scheduler_reject",
      "requests_scheduler_ai_summary",
    ],
  },
  {
    id: "data_tools",
    label: "ΕΡΓΑΛΕΙΑ ΔΕΔΟΜΕΝΩΝ",
    keys: [
      "data_tools_view",
      "data_tools_bulk_delete",
      "data_tools_bulk_edit",
      "data_tools_export_vcf",
      "data_tools_export_excel",
    ],
  },
  {
    id: "campaigns",
    label: "ΚΑΜΠΑΝΙΕΣ",
    keys: ["campaigns_view", "campaigns_create", "campaigns_start"],
  },
  {
    id: "tools",
    label: "ΕΡΓΑΛΕΙΑ & MODULES",
    keys: [
      "tasks_view",
      "tasks_create",
      "tasks_assign",
      "analytics_view",
      "documents_view",
      "documents_upload",
      "events_view",
      "events_create",
      "volunteers_view",
      "polls_view",
      "polls_create",
      "retell_call",
      "whatsapp_send",
      "export_data",
    ],
  },
  {
    id: "alexandra",
    label: "ΑΛΕΞΑΝΔΡΑ — ΓΕΝΙΚΑ",
    keys: [
      "alexandra_use",
      "alexandra_bulk_delete",
      "alexandra_bulk_update",
      "alexandra_import",
    ],
  },
  {
    id: "alexandra_tools",
    label: "ΑΛΕΞΑΝΔΡΑ — ΕΡΓΑΛΕΙΑ CHAT",
    keys: [
      "alexandra_tool_bulk_delete_contacts",
      "alexandra_tool_bulk_update_contacts",
      "alexandra_tool_start_campaign",
      "alexandra_tool_send_whatsapp",
      "alexandra_tool_export_contacts",
      "alexandra_tool_create_user",
      "alexandra_tool_delete_data",
    ],
  },
  {
    id: "access",
    label: "ΑΣΦΑΛΕΙΑ ΠΡΟΣΒΑΣΗΣ",
    keys: ["access_code_view", "access_code_revoke"],
  },
  {
    id: "settings",
    label: "ΡΥΘΜΙΣΕΙΣ",
    keys: ["settings_view", "settings_edit", "users_manage", "roles_manage"],
  },
] as const;

export const PERMISSION_LABELS: Record<PermissionKey, string> = {
  contacts_view: "Προβολή επαφών",
  contacts_create: "Δημιουργία επαφών",
  contacts_edit: "Επεξεργασία επαφών",
  contacts_delete: "Διαγραφή επαφών",
  contacts_export: "Εξαγωγή επαφών",
  contacts_import: "Εισαγωγή επαφών",
  contacts_bulk: "Μαζικές ενέργειες επαφών",
  requests_view: "Προβολή αιτημάτων",
  requests_create: "Δημιουργία αιτημάτων",
  requests_edit: "Επεξεργασία αιτημάτων",
  requests_delete: "Διαγραφή αιτημάτων",
  requests_complete: "Ολοκλήρωση αιτήματος (γρήγορη)",
  requests_reject: "Απόρριψη αιτήματος",
  requests_assign: "Ανάθεση αιτήματος",
  requests_scheduler_view: "Προγραμματισμός — προβολή",
  requests_scheduler_schedule: "Προγραμματισμός — χρονοπρογραμματισμός",
  requests_scheduler_complete: "Προγραμματισμός — ολοκλήρωση",
  requests_scheduler_reject: "Προγραμματισμός — απόρριψη",
  requests_scheduler_ai_summary: "Προγραμματισμός — AI περίληψη",
  data_tools_view: "Εργαλεία δεδομένων — προβολή",
  data_tools_bulk_delete: "Εργαλεία — μαζική διαγραφή",
  data_tools_bulk_edit: "Εργαλεία — μαζική επεξεργασία",
  data_tools_export_vcf: "Εξαγωγή vCard",
  data_tools_export_excel: "Εξαγωγή Excel",
  access_code_view: "Κλειδαριθμός — προβολή",
  access_code_revoke: "Κλειδαριθμός — ανάκληση",
  communication_logs_delete: "Διαγραφή καταγραφών επικοινωνίας",
  ai_summary_view: "AI σύνοψη — προβολή",
  campaigns_view: "Προβολή καμπανιών",
  campaigns_create: "Δημιουργία καμπανιών",
  campaigns_start: "Εκκίνηση κλήσεων καμπάνιας",
  tasks_view: "Προβολή εργασιών",
  tasks_create: "Δημιουργία εργασιών",
  tasks_assign: "Ανάθεση εργασιών",
  analytics_view: "Αναλυτικά",
  documents_view: "Έγγραφα — προβολή",
  documents_upload: "Έγγραφα — μεταφόρτωση",
  settings_view: "Ρυθμίσεις — προβολή",
  settings_edit: "Ρυθμίσεις — επεξεργασία",
  users_manage: "Διαχείριση χρηστών",
  roles_manage: "Διαχείριση ρόλων",
  events_view: "Εκδηλώσεις — προβολή",
  events_create: "Εκδηλώσεις — δημιουργία",
  volunteers_view: "Εθελοντές",
  polls_view: "Δημοσκοπήσεις — προβολή",
  polls_create: "Δημοσκοπήσεις — δημιουργία",
  alexandra_use: "Χρήση Αλεξάνδρας",
  alexandra_bulk_delete: "Αλεξάνδρα — μαζική διαγραφή",
  alexandra_bulk_update: "Αλεξάνδρα — μαζική ενημέρωση",
  alexandra_import: "Αλεξάνδρα — εισαγωγή",
  alexandra_tool_bulk_delete_contacts: "Εργαλείο: μαζική διαγραφή επαφών",
  alexandra_tool_bulk_update_contacts: "Εργαλείο: μαζική ενημέρωση επαφών",
  alexandra_tool_start_campaign: "Εργαλείο: εκκίνηση καμπάνιας",
  alexandra_tool_send_whatsapp: "Εργαλείο: WhatsApp",
  alexandra_tool_export_contacts: "Εργαλείο: εξαγωγή επαφών",
  alexandra_tool_create_user: "Εργαλείο: δημιουργία χρήστη",
  alexandra_tool_delete_data: "Εργαλείο: διαγραφή δεδομένων",
  retell_call: "Retell — κλήσεις",
  whatsapp_send: "WhatsApp — αποστολή",
  export_data: "Εξαγωγή δεδομένων (εργαλεία)",
};

export const ALEXANDRA_TOOL_KEYS = PERMISSION_CATEGORIES.find((c) => c.id === "alexandra_tools")!.keys;

/** Dev-only: every canonical key must appear in categories and tooltips. */
function assertPermissionCatalogComplete() {
  const inCategories = new Set(PERMISSION_CATEGORIES.flatMap((c) => c.keys));
  for (const key of ALL_PERMISSION_KEYS) {
    if (!inCategories.has(key)) throw new Error(`Permission missing from categories: ${key}`);
    if (!PERMISSION_TOOLTIPS[key]) throw new Error(`Permission missing tooltip: ${key}`);
  }
  const categoryCount = PERMISSION_CATEGORIES.reduce((n, c) => n + c.keys.length, 0);
  if (categoryCount !== ALL_PERMISSION_KEYS.length) {
    throw new Error(`Category key count (${categoryCount}) !== ALL_PERMISSION_KEYS (${ALL_PERMISSION_KEYS.length})`);
  }
}

if (process.env.NODE_ENV !== "production") {
  assertPermissionCatalogComplete();
}
